version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    links:
      - zookeeper
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "test:1:1" # 1 partition, 1 replica
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  fix-cassandra-permissions:
    image: bitnami/cassandra:latest
    user: root
    command: chown -R 1001:1001 /bitnami
    volumes:
      - /home/safa/Projects/Proente/Morpheus/cassandra:/bitnami
  cassandra:
    image: bitnami/cassandra:latest
    container_name: cassandra
    hostname: cassandra
    ports:
      - "9042:9042"
    volumes:
      - /home/safa/Projects/Proente/Morpheus/cassandra:/bitnami
    depends_on:
      - fix-cassandra-permissions
  spark-master:
    image: bde2020/spark-master:2.4.0-hadoop2.7
    hostname: spark-master
    container_name: spark-master
    ports:
      - "8080:8080" # spark master
      - "7077:7077" # ?
      - "4040:4040" # app gui
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - "constraint:node==spark-master"
    volumes:
      - /home/safa/Projects/Proente/Morpheus/target/scala-2.11/MorpheusML-assembly-0.1.jar:/MorpheusML-assembly-0.1.jar
  spark-worker-1:
    image: bde2020/spark-worker:2.4.0-hadoop2.7
    hostname: spark-worker-1
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==spark-worker-1"
      - SPARK_WORKER_CORES=5
      - SPARK_WORKER_MEMORY=4G
      - SPARK_DRIVER_MEMORY=128m
      - SPARK_EXECUTOR_MEMORY=256m
  spark-worker-2:
    image: bde2020/spark-worker:2.4.0-hadoop2.7
    hostname: spark-worker-2
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==spark-worker-2"
      - SPARK_WORKER_CORES=5
      - SPARK_WORKER_MEMORY=4G
      - SPARK_DRIVER_MEMORY=128m
      - SPARK_EXECUTOR_MEMORY=256m
  go-app:
    image: go-kafka-connector:latest
    depends_on:
      - kafka
    volumes:
      - /home/safa/Projects/Proente/RabbitmqToKafkaGoExample:/app
    working_dir: /app