version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - "2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    expose:
      - "9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      #  KAFKA_CREATE_TOPICS: "test:1:1,Topic-1-2:1:2,Topic-2-2:2:2,Topic-2-1:2:1,Topic-1-1:1:1" # topic:#partition:#replica
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  fix_cassandra_permissions:
    image: bitnami/cassandra:latest
    user: root
    command: chown -R 1001:1001 /bitnami
    volumes:
      - ~/Proente/DockerVolumes/cassandra/db:/bitnami

  cassandra:
    image: bitnami/cassandra:latest
    expose:
      - "9042"
    # change below paths considering your own environment
    volumes:
      - ~/Proente/DockerVolumes/cassandra/db:/bitnami
      - ~/Proente/DockerVolumes/cassandra/init_scripts:/docker-entrypoint-initdb.d
    depends_on:
      - fix_cassandra_permissions

  spark_master:
    image: bde2020/spark-master:2.4.0-hadoop2.7
    hostname: spark-master
    container_name: spark-master
    expose:
      - "8080"
      - "7077"
      - "4040"
    ports:
      - "8080:8080" # spark master
      - "7077:7077" # ?
      - "4040:4040" # app gui
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - "constraint:node==spark-master"
    # change below paths considering your own environment
    volumes:
      - ~/Proente/DockerVolumes/spark_master/MorpheusML-assembly-0.1.jar:/MorpheusML-assembly-0.1.jar 

  spark_worker:
    image: bde2020/spark-worker:2.4.0-hadoop2.7
    depends_on:
      - spark_master
    expose:
      - "8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      # - "constraint:node==spark-worker-1" # this configuration is for running spark on mesos
      - SPARK_WORKER_CORES=5
      - SPARK_WORKER_MEMORY=4G
      - SPARK_DRIVER_MEMORY=128m
      - SPARK_EXECUTOR_MEMORY=256m

  go_app:
    image: go-kafka-connector:latest
    depends_on:
      - kafka
    environment:
      - QUEUE_NAME=processed_machine_action_notif
